dipsycat_blog_homepage:
    path:     /
    defaults: { _controller: DipsycatBlogBundle:Home:index }
dipsycat_blog_admin:
    path:     /admin-my
    defaults: { _controller: DipsycatBlogBundle:Default:index }
