services:
    dispsycat_blog.login_submit:
        class: Dipsycat\BlogBundle\EventListener\LoginSubmitListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }
    admin.user:
        class: Dipsycat\BlogBundle\Admin\UserAdmin
        arguments: [~, Dipsycat\BlogBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }
        public: true
    admin.post:
        class: Dipsycat\BlogBundle\Admin\PostAdmin
        arguments: [~, Dipsycat\BlogBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Post }
        public: true
