services:
    admin.post:
        class: Dipsycat\PostBundle\Admin\PostAdmin
        arguments: [~, Dipsycat\PostBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Post }
        public: true